export const products = [
  {
    id: "1",
    title: "Basic Tee 1",
    colors: ["#000000", "#FFFFFF", "#808080", "#001F3F"],
    sizes: ["S", "M", "L", "XL"],
    price: 35,
    image: "/longsleave.png",
    description:
      "A soft and comfortable everyday t-shirt made with premium cotton.\nPerfect for casual wear and layering in all seasons.",
  },
  {
    id: "2",
    title: "Basic Tee 2",
    colors: ["#FFFFFF", "#000000", "#F5F5DC", "#87CEEB"],
    sizes: ["S", "M", "L", "XL"],
    price: 36,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg",
    description:
      "A clean and minimal tee designed for a modern look.\nBreathable fabric ensures all-day comfort and ease.",
  },
  {
    id: "3",
    title: "Basic Tee 3",
    colors: ["#0000FF", "#ADD8E6", "#FFFFFF", "#36454F"],
    sizes: ["S", "M", "L", "XL"],
    price: 37,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg",
    description:
      "A stylish tee with a relaxed fit for daily use.\nDurable stitching makes it long-lasting and reliable.",
  },
  {
    id: "4",
    title: "Basic Tee 4",
    colors: ["#808080", "#000000", "#C0C0C0", "#FFFFFF"],
    sizes: ["S", "M", "L", "XL"],
    price: 38,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg",
    description:
      "A neutral-toned t-shirt that matches every outfit.\nSoft texture gives a premium feel on the skin.",
  },
  {
    id: "5",
    title: "Basic Tee 5",
    colors: ["#008000", "#808000", "#000000", "#FFFFFF"],
    sizes: ["S", "M", "L", "XL"],
    price: 39,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-01.jpg",
    description:
      "A fresh and vibrant tee inspired by nature tones.\nIdeal for outdoor wear and casual styling.",
  },
  {
    id: "6",
    title: "Basic Tee 6",
    colors: ["#FF0000", "#800000", "#000000", "#FFFFFF"],
    sizes: ["S", "M", "L", "XL"],
    price: 40,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-02.jpg",
    description:
      "A bold and energetic t-shirt for standout looks.\nComfortable fit with long-lasting color quality.",
  },
  {
    id: "7",
    title: "Basic Tee 7",
    colors: ["#000080", "#0000FF", "#FFFFFF", "#808080"],
    sizes: ["S", "M", "L", "XL"],
    price: 41,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-03.jpg",
    description:
      "A deep-toned tee offering a smart casual vibe.\nPerfect blend of comfort and everyday style.",
  },
  {
    id: "8",
    title: "Basic Tee 8",
    colors: ["#A52A2A", "#F5F5DC", "#000000", "#FFFDD0"],
    sizes: ["S", "M", "L", "XL"],
    price: 42,
    image:
      "https://tailwindcss.com/plus-assets/img/ecommerce-images/product-page-01-related-product-04.jpg",
    description:
      "A warm earthy-toned t-shirt for a premium look.\nSoft fabric ensures maximum comfort all day long.",
  },
];

export const ordersData = [
  {
    id: 1,
    orderId: "ORD-20260701-1001",
    orderName: "Apple iPhone 15 Pro Max",
    date: "01-07-2026",
    price: 1899,
    status: "Pending",
    customer: "Muhammad Ali",
    paymentMethod: "Credit Card",
    items: 1,
  },
  {
    id: 2,
    orderId: "ORD-20260701-1002",
    orderName: "Samsung Galaxy S25 Ultra",
    date: "01-07-2026",
    price: 1499,
    status: "Confirmed",
    customer: "Ahmed Khan",
    paymentMethod: "Cash on Delivery",
    items: 1,
  },
  {
    id: 3,
    orderId: "ORD-20260701-1003",
    orderName: "Sony WH-1000XM6 Headphones",
    date: "30-06-2026",
    price: 399,
    status: "Processing",
    customer: "Usman Tariq",
    paymentMethod: "Debit Card",
    items: 2,
  },
  {
    id: 4,
    orderId: "ORD-20260701-1004",
    orderName: "Dell XPS 15 Laptop",
    date: "29-06-2026",
    price: 2499,
    status: "Out for Delivery",
    customer: "Bilal Ahmed",
    paymentMethod: "Bank Transfer",
    items: 1,
  },
  {
    id: 5,
    orderId: "ORD-20260701-1005",
    orderName: "Apple Watch Series 10",
    date: "28-06-2026",
    price: 599,
    status: "Delivered",
    customer: "Hassan Raza",
    paymentMethod: "Credit Card",
    items: 1,
  },
  {
    id: 6,
    orderId: "ORD-20260701-1006",
    orderName: "Logitech MX Master 4",
    date: "27-06-2026",
    price: 129,
    status: "Completed",
    customer: "Ali Hassan",
    paymentMethod: "Cash on Delivery",
    items: 1,
  },
  {
    id: 7,
    orderId: "ORD-20260701-1007",
    orderName: "PlayStation 5 Slim",
    date: "26-06-2026",
    price: 699,
    status: "Cancelled",
    customer: "Saad Malik",
    paymentMethod: "Debit Card",
    items: 1,
  },
  {
    id: 8,
    orderId: "ORD-20260701-1008",
    orderName: "Nike Air Max 2026",
    date: "25-06-2026",
    price: 220,
    status: "Returned",
    customer: "Fahad Khan",
    paymentMethod: "Credit Card",
    items: 2,
  },
  {
    id: 9,
    orderId: "ORD-20260701-1009",
    orderName: "Canon EOS R8 Camera",
    date: "24-06-2026",
    price: 1799,
    status: "Failed Delivery",
    customer: "Hamza Shah",
    paymentMethod: "Cash on Delivery",
    items: 1,
  },
  {
    id: 10,
    orderId: "ORD-20260701-1010",
    orderName: "ASUS ROG Strix G16",
    date: "23-06-2026",
    price: 2199,
    status: "On Hold",
    customer: "Awais Ahmad",
    paymentMethod: "Bank Transfer",
    items: 1,
  },
];
